
const Data = [
    {
        id:"1",
        title:"test1",
        category: "Do an sang trong",
        region: "Mon A",
        img:"https://media.saigontourist.edu.vn/Media/1_STHCHOME/FolderFunc/202305/Images/tom-yum-thai-lan-20230509104209-e.jpg",
        desc:"test 1",
        cooking_time:"1 phut",
    },
    {
        id:"2",
        title:"test2",
        category: "Do an sang trong",
        region: "Mon A",
        img:"https://media.saigontourist.edu.vn/Media/1_STHCHOME/FolderFunc/202305/Images/salad-la-tra-myanmar-20230509104249-e.jpg",
        desc:"test 2",
        cooking_time:"2 phut",
    },
    {
        id:"3",
        title:"test3",
        category: "Do an sang trong",
        region: "Mon Au",
        img:"https://media.saigontourist.edu.vn/Media/1_STHCHOME/FolderFunc/202305/Images/thit-bo-kobe-nhat-ban-20230509104324-e.jpg",
        desc:"test 3",
        cooking_time:"3 phut",
    },
    {
        id:"4",
        title:"test4",
        category: "Do an sang trong",
        region: "Do an Viet Nam",
        img:"https://media.saigontourist.edu.vn/Media/1_STHCHOME/FolderFunc/202305/Images/tom-yum-thai-lan-20230509104209-e.jpg",
        desc:"test 4",
        cooking_time:"4 phut",
    },
    {
        id:"5",
        title:"test5",
        category: "Do an sang trong",
        region: "Mon trung",
        img:"https://media.saigontourist.edu.vn/Media/1_STHCHOME/FolderFunc/202305/Images/tom-yum-thai-lan-20230509104209-e.jpg",
        desc:"test 5",
        cooking_time:"5 phut",
    },
    {
        id:"6",
        title:"test6",
        category: "Do an sang trong",
        region: "Mon A",
        img:"https://media.saigontourist.edu.vn/Media/1_STHCHOME/FolderFunc/202305/Images/tom-yum-thai-lan-20230509104209-e.jpg",
        desc:"test 6",
        cooking_time:"6 phut",
    },
    {
        id:"7",
        title:"test7",
        category: "Do an taam thuong",
        region: "Mon A",
        img:"https://media.saigontourist.edu.vn/Media/1_STHCHOME/FolderFunc/202305/Images/tom-yum-thai-lan-20230509104209-e.jpg",
        desc:"test 7",
        cooking_time:"7 phut",
    },
    {
        id:"8",
        title:"test8",
        category: "Bua trua",
        region: "Mon A",
        img:"https://media.saigontourist.edu.vn/Media/1_STHCHOME/FolderFunc/202305/Images/tom-yum-thai-lan-20230509104209-e.jpg",
        desc:"test 8",
        cooking_time:"8 phut",
    },
    {
        id:"9",
        title:"test9",
        category: "Bua sang",
        region: "Mon A",
        img:"https://media.saigontourist.edu.vn/Media/1_STHCHOME/FolderFunc/202305/Images/pho-viet-nam-20230509104248-e.jpg",
        desc:"test 9",
        cooking_time:"9 phut",
    }
];

export default Data;